### ISSUE TITLE
v. 0.1.1 - Cannot read property 'MaxRequest' of null

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#8] opened 2015-02-05 15:27 UTC
In the new version it try to read property MaxRequest of null. It happens when you drag or select files to upload.

![2015-02-05_16-22-36](https://cloud.githubusercontent.com/assets/2919859/6062937/dd806aa0-ad53-11e4-88ac-240d6c124693.jpg)

**Comment by ProfessorFarnsworth** [comment] 2015-02-05 16:06
Hi,
I'm sorry for that bad update! Unfortunately I can't reproduce this issue in my environment.
But I've checked in a test build with a fix for this issue. Could you try to download it an manually copy it over the one in the bin folder on your system? The new dll can be found in the repo under https://github.com/ProfessorFarnsworth/HTML-5-File-Upload/tree/master/HTML5%20File%20Upload/bin/Debug

Thanks for testing!

**Comment by bjarnef** [comment] 2015-02-05 16:18
Hi... it didn't seem to fix the problem..

I think the issue should be found here: https://github.com/ProfessorFarnsworth/HTML-5-File-Upload/blob/master/HTML5%20File%20Upload/App_Plugins/FileUpload/js/fileupload.controller.js#L91

check that $scope.settings is not null, before read property MaxRequest.

**Comment by bjarnef** [comment] 2015-02-05 16:21
Maybe it is because in my case the max limit isn't set in web.config? Then the default should be 4 MB.

**Comment by ProfessorFarnsworth** [comment] 2015-02-05 16:25
Would be a workaround but that kills my file size check :(
Maybe I need to implement a "Control loading spinner" until the server responded with the right message.
Maybe you could try to wait ~1 minute before adding files for the upload. If it works it might be a timing issue.
Thanks again!

**Comment by bjarnef** [comment] 2015-02-05 16:28
but I notice when loading the media section I get these errors in console:

GET http://umb7.bjarnefyrstenborg.dk/umbraco/%7B%7Bimg.ImageUrl%7D%7D 404 (Not Found)
GET http://umb7.bjarnefyrstenborg.dk/umbraco/backoffice/api/Html5FileUpload/GetSettings 500 (Internal Server Error)
GET http://umb7.bjarnefyrstenborg.dk/umbraco/backoffice/api/Html5FileUpload/GetContent?parentId=1098 500 (Internal Server Error)

**Comment by ProfessorFarnsworth** [comment] 2015-02-05 16:39
Seems that there is something completely going wrong! Hopefully I can reproduce this issue on another installation. I'll try to get back to you asap.
Anyway thank you very much for your patience and your time!

**Comment by bjarnef** [comment] 2015-02-05 16:50
Do you run the installation with debug=true og debug=false?
Ensure it works with debug=false .. I think we had some issues with latest version of Analytics because of ClientDependency Framework, so it required debug=true.

However in my Umbraco 7.2.0 I got some other error in console with debug=true.

**Comment by bjarnef** [comment] 2015-02-05 16:56
Maybe you should mark the ApiController as a PluginController for backoffice shipped with the package?
```[PluginController("AwesomeProducts")]```

**Comment by bjarnef** [comment] 2015-02-05 17:03
Noticed a small typo in virtual path :) https://github.com/ProfessorFarnsworth/HTML-5-File-Upload/blob/master/HTML5%20File%20Upload/Html5FileUploadController.cs#L74

**Comment by ProfessorFarnsworth** [comment] 2015-02-05 17:50
Thanks for your help! I've just uploaded a new package which should contain a fix for that problem.
I also corrected that typo :)

**Comment by bjarnef** [comment] 2015-02-05 18:07
Great :+1: 
I am not sure if this error in console is because of the package?
GET http://umb7.bjarnefyrstenborg.dk/umbraco/%7B%7Bimg.ImageUrl%7D%7D 404 (Not Found)

and when clicking "select files" button I get this error in console:
Error: $apply already in progress

and in (File is to large for upload.) it is missing a "o", so "too". :)
Furthermore, maybe just round the calculated percent during upload to a whole number? instead of
Style_4.jpg - 86.15174210104743%  ... and it ends with 100%

otherwise it works great and upload the files again :)

**Comment by ProfessorFarnsworth** [comment] 2015-02-05 18:20
Thanks for the test and your patience :)
Great to hear that it is working again!

The 404 is an issue caused by my binding in angular which I gonna fix right now. (Never bind src="{{img.ImageUrl"}} - always use ng-src="{{img.ImageUrl"}}" :D)

The typo is corrected (I swear one day i gonna learn how to write stuff)

Well the percentage is also fixed now :)

**Closed by ProfessorFarnsworth** 2015-02-05 18:20 UTC
Labels: bug

**Comment by bjarnef** [comment] 2015-02-05 18:24
Yeah, always use ng- for AngularJS stuff.. in Umbraco's Grid style work in Chrome but IE doesn't like AngularJS binding here.. and therefore I think it has been changed to ng-style.

Great.. nice work! ;)
